
POST http://localhost:8888/api/createLink
Content-Type: application/json

{
    "name" : "dana",
    "url" : "https://github.com/", 
    "description" : "abc"
}

###
GET http://localhost:8888/api/getLinks
